version: "1.0"
info:
  model: int-scaffold
packages:
- name: Kvv_1506_AWSPPProject
  gitServerName: kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: SIQA_OriginTest_OnPremAssets
  version: "1.0"
  gitServerName: SIQABitbucketTest
  gitUrl: https://bitbucket.org/siqamjan
  gitUsername: siqagituser
  gitBranch: Test
- name: SIQAJDBCAdapterTests
  version: "1.0"
  gitServerName: MJANGit
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
- name: SIQACloudStreamsTests
  version: "1.0"
  gitServerName: MJANGit
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
- name: JMSTest
  version: "1.0"
  gitServerName: kvv
  gitUrl: https://github.com/prabhakarsag
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
- name: WmJDBCAdapter
  version: 10.3.0.0.34
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
- name: TPP_services_in_FCS
  gitServerName: kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
services:
- serviceName: project.kvv_1506_awspp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:mssql
  packages:
  - name: Kvv_1506_AWSPPProject
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 12.0.0.0.22
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: project.kvv_1506_awspp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:TestDBConn
  packages:
  - name: Kvv_1506_AWSPPProject
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 12.0.0.0.22
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: project.kvv_1506_awspp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:test
  packages:
  - name: Kvv_1506_AWSPPProject
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 12.0.0.0.22
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: project.kvv_1506_awspp.integrations:JMSFlowTest
  packages:
  - name: Kvv_1506_AWSPPProject
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 12.0.0.0.22
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: publisher:publisher
  packages:
  - name: JMSTest
    version: "1.0"
- serviceName: pub.jms:send
  packages:
  - name: WmPublic
    version: 12.1.0.0.828
- serviceName: project.kvv_1506_awspp.integrations:SIQAAdapterFlow
  packages:
  - name: Kvv_1506_AWSPPProject
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 12.0.0.0.22
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: project.kvv_1506_awspp.integrations:refdaf
  packages:
  - name: Kvv_1506_AWSPPProject
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 12.0.0.0.22
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: project.kvv_1506_awspp.referencedata:ref1
  packages:
  - name: Kvv_1506_AWSPPProject
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 12.0.0.0.22
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: project.kvv_1506_awspp.integrations:switchCaseDADA
  packages:
  - name: Kvv_1506_AWSPPProject
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 12.0.0.0.22
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 12.1.0.0.828
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 12.1.0.0.828
- serviceName: project.kvv_1506_awspp.integrations:tppdaf
  packages:
  - name: Kvv_1506_AWSPPProject
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
  - name: JMSTest
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 12.0.0.0.22
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: Basics_1:ComplexFS
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: Basics_1:Basic_Flow
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: pub.math:divideInts
  packages:
  - name: WmPublic
    version: 12.1.0.0.828
- serviceName: pub.math:subtractInts
  packages:
  - name: WmPublic
    version: 12.1.0.0.828
- serviceName: pub.math:multiplyIntList
  packages:
  - name: WmPublic
    version: 12.1.0.0.828
- serviceName: Basics_1:mapservice
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: Basics_1:TryCatch
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: Map_1:TestFlow
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: REST_1_1.CurrentDateAndTime:_get
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 12.1.0.0.828
- serviceName: pub.string:objectToString
  packages:
  - name: WmPublic
    version: 12.1.0.0.828
- serviceName: SOAP_1_1:showDateAndTime
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
configurationVariables:
  jdbc.SAP TxStore Pool.maxConns: "10"
  ? artConnection.Kvv_1506_AWSPPProject.project.kvv_1506_awspp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mssql.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.Kvv_1506_AWSPPProject.project.kvv_1506_awspp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mssql.connectionSettings.user
  : sa
  jdbcfunc.SAPTxStore.failFastMode: false
  jdbc.SAP TxStore Pool.poolThreshold: "0"
  ? artConnection.Kvv_1506_AWSPPProject.project.kvv_1506_awspp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mssql.connectionManagerSettings.poolable
  : "false"
  jdbc.SAP TxStore Pool.spyenabled: "false"
  ? artConnection.Kvv_1506_AWSPPProject.project.kvv_1506_awspp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mssql.connectionSettings.dbType
  : MSSQL
  ? artConnection.Kvv_1506_AWSPPProject.project.kvv_1506_awspp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mssql.connectionSettings.trustStore
  : ""
  jdbc.SAP TxStore Pool.useSSL: "false"
  jdbc.SAP TxStore Pool.password: "{AES}nrGf3u7Wt20hFBGh5ZeEuQ=="
  ? artConnection.Kvv_1506_AWSPPProject.project.kvv_1506_awspp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mssql.connectionSettings.driverType
  : Progress® DataDirect®
  ? artConnection.Kvv_1506_AWSPPProject.project.kvv_1506_awspp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mssql.connectionSettings.transactionType
  : NO_TRANSACTION
  jdbc.SAP TxStore Pool.spyparms: SpyAttributes=(log=(file)logs/spy/SAP_TxStore_Pool.log;logTName=yes;timestamp=yes)
  ? artConnection.Kvv_1506_AWSPPProject.project.kvv_1506_awspp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mssql.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.Kvv_1506_AWSPPProject.project.kvv_1506_awspp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mssql.connectionManagerSettings.heartBeatInterval
  : "0"
  jdbc.SAP TxStore Pool.snoopenabled: "false"
  ? artConnection.Kvv_1506_AWSPPProject.project.kvv_1506_awspp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mssql.connectionManagerSettings.startupRetryCount
  : "0"
  jdbc.SAP TxStore Pool.expireTime: "60000"
  jdbc.SAP TxStore Pool.minConns: "5"
  ? artConnection.Kvv_1506_AWSPPProject.project.kvv_1506_awspp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mssql.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.sqlserver.SQLServerDataSource
  jdbc.SAP TxStore Pool.driverAlias: MySQL CC Driver
  ? artConnection.Kvv_1506_AWSPPProject.project.kvv_1506_awspp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mssql.connectionSettings.portNumber
  : "1433"
  jdbcfunc.SAPTxStore.connPoolAlias: SAP TxStore Pool
  ? artConnection.Kvv_1506_AWSPPProject.project.kvv_1506_awspp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mssql.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.Kvv_1506_AWSPPProject.project.kvv_1506_awspp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mssql.connectionSettings.networkProtocol
  : tcp
  ? artConnection.Kvv_1506_AWSPPProject.project.kvv_1506_awspp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mssql.connectionSettings.serverName
  : 9.60.195.99
  ? artConnection.Kvv_1506_AWSPPProject.project.kvv_1506_awspp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mssql.connectionSettings.keyStore
  : ""
  ? artConnection.Kvv_1506_AWSPPProject.project.kvv_1506_awspp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mssql.connectionSettings.password
  : "{AES}X4QCAWgjWkTdMQvFA5XaqGmK1wuN3U1rA1B0VhuZoUw="
  jdbc.SAP TxStore Pool.dbURL: jdbc:mysql://localhost:3306/SAPTRANSACTIONSTORE?useSSL=false&characterEncoding=utf-8&autoReconnect=true&maxReconnects=5&sessionVariables=wait_timeout=2147483
  jdbc.SAP TxStore Pool.waitingThread: "10"
  jdbc.SAP TxStore Pool.description: Connection Pool for the SAP Transaction Store
  ? artConnection.Kvv_1506_AWSPPProject.project.kvv_1506_awspp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mssql.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.Kvv_1506_AWSPPProject.project.kvv_1506_awspp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mssql.connectionSettings.databaseName
  : SIQACloud
  jdbc.SAP TxStore Pool.snoopparms: ddtdbg.ProtocolTraceEnable=true;ddtdbg.ProtocolTraceMaxline=16;ddtdbg.ProtocolTraceLocation=logs/snoop/SAP_TxStore_Pool.log;ddtdbg.ProtocolTraceShowTime=true
  ? artConnection.Kvv_1506_AWSPPProject.project.kvv_1506_awspp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mssql.connectionManagerSettings.poolIncrementSize
  : "1"
  jdbc.SAP TxStore Pool.userid: root
  ? artConnection.Kvv_1506_AWSPPProject.project.kvv_1506_awspp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mssql.connectionEnabled
  : "false"
  ? artConnection.Kvv_1506_AWSPPProject.project.kvv_1506_awspp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mssql.connectionSettings.otherProperties
  : loginTimeout=60;driverType=thin;
  ? artConnection.Kvv_1506_AWSPPProject.project.kvv_1506_awspp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.mssql.connectionManagerSettings.startupBackoffSecs
  : "10"
